import Feedback from "./Feedback";

/**
 * Error generated by this application.
 */
export default class AppError extends Error {
    private errorFeedback: Feedback;

    /**
     * Creates application error.
     * 
     * @param errorFeedback Feedback to be sent to user.
     */
    constructor(errorFeedback: Feedback) {
        super()
        this.errorFeedback = errorFeedback;
    }

    /**
     * Gets error feedback.
     * 
     * @returns Error feedback as string.
     */
    public getMessage() {
        return this.errorFeedback.toString();
    }
}